# Generated by Django 4.2.28 on 2026-02-21 22:41

from django.db import migrations, models
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_remove_task_is_completed_task_assignee_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(default='No description provided', validators=[projects.models.validate_min_length]),
            preserve_default=False,
        ),
    ]
